FancyFreeze_Config:
  ConfigVersion: 1
  Messages:
    Prefix: "<gradient:#00E0FF:#008EFF><bold>FancyFreeze</bold></gradient> <gray>» "
    RELOAD: "<gradient:#00FF64:#8AFF00>✦ Config successfully reloaded."
    NO_SELF_FREEZE: "<gradient:#F51010:#FF0091>⚠ You cannot freeze yourself!"
    PLAYER_HAS_PERM: "<gradient:#F51010:#FF0091>⚠ This player is immune to freezing!"
    PLAYER_ALREADY_FROZEN: "<gradient:#F51010:#FF0091>⚠ That player is already frozen."
    PLAYER_FROZEN: "<gradient:#00FF64:#8AFF00>❄ The player's movement has been <gradient:#F51010:#FF0091><bold>disabled</bold><gradient:#00FF64:#8AFF00>"
    PLAYER_UNFROZEN: "<gradient:#00FF64:#8AFF00>☀ The player's movement has been <gradient:#007725:#00CF5A><bold>enabled</bold><gradient:#00FF64:#8AFF00>"
    FROZEN_BY: "<gradient:#F51010:#FF0091>❄ You've been frozen by <underlined><sender></underlined>."
    UNFROZEN_BY: "<gradient:#00FF64:#8AFF00>☀ You've been unfrozen by <gradient:#007725:#00CF5A><sender></gradient><gradient:#00FF64:#8AFF00>."
    NO_FREEZABLE: "<gradient:#F51010:#FF0091>⚠ There are no freezable players online."
    ALL_PLAYERS_FROZEN: "<gradient:#00FF64:#8AFF00>❄ All players have been frozen."
    ALL_PLAYERS_UNFROZEN: "<gradient:#00FF64:#8AFF00>☀ All players have been unfrozen."
    STAFF_NOTICE: "<gradient:#00FF64:#8AFF00>⚑ <gradient:#007725:#00CF5A><target> </gradient><gradient:#00FF64:#8AFF00>has been frozen by <gradient:#007725:#00CF5A><sender><gradient:#00FF64:#8AFF00>."
    STAFF_NOTICE_ALL: "<gradient:#00FF64:#8AFF00>⚑ All players have been frozen by <gradient:#007725:#00CF5A><sender><gradient:#00FF64:#8AFF00>."
    STAFF_NOTICE_UN: "<gradient:#00FF64:#8AFF00>⚑ <gradient:#007725:#00CF5A><target> <gradient:#00FF64:#8AFF00>has been unfrozen by <gradient:#007725:#00CF5A><sender><gradient:#00FF64:#8AFF00>."
    STAFF_NOTICE_ALL_UN: "<gradient:#00FF64:#8AFF00>⚑ All players have been unfrozen by <gradient:#007725:#00CF5A><sender><gradient:#00FF64:#8AFF00>."
    PLAYER_NOT_FROZEN: "<gradient:#F51010:#FF0091>⚠ That player is not currently frozen."
    NO_PLAYER_FROZEN: "<gradient:#F51010:#FF0091>⚠ No players are currently frozen."
    FROZEN_ACTION_BAR: "<gradient:#008EFF:#00E0FF><bold>❄ YOU ARE FROZEN ❄</bold>"
    CANT_HIT_FROZEN_PLAYER: "<gradient:#F51010:#FF0091>⚠ That player is frozen, you cannot hit them."
    NO_COMMAND: "<gradient:#F51010:#FF0091>⚠ Commands are disabled while you are frozen."
    NO_CHAT: "<gradient:#F51010:#FF0091>⚠ Chat is disabled while you are frozen."
  Features:
    BSTATS: TRUE
    CHECK_FOR_UPDATES: TRUE
    SPAWN_PARTICLES: TRUE
    FREEZE_EFFECT: TRUE
    GLOWING_EFFECT: TRUE
    ACTION_BAR_MSG: TRUE
    BLOCK_PLAYER_MOVE: TRUE
    BLOCK_PLAYER_INTERACT: TRUE
    BLOCK_PLAYER_HIT: TRUE
    BLOCK_ITEM_DROP: TRUE
    BLOCK_ITEM_PICKUP: TRUE
    BLOCK_INTERACTING_WITH_ENTITY: TRUE
    BLOCK_INVENTORY_CLICK: TRUE
    BLOCK_ITEM_SWAP: TRUE
    BLOCK_PLAYER_DAMAGE: TRUE
    BLOCK_GUI_OPEN: TRUE
    BLOCK_TELEPORT: FALSE
    BLOCK_CHAT: FALSE
    #Cmd to be run by the srv if a player leaves while frozen. <player> will refer to the player who left. To run multiple cmds, separate them with ";". For ex.: say <player> has been banned!;ban <player>;
    COMMAND_ON_LEAVE: ""
    BLOCK_PLAYER_COMMANDS: TRUE
    #Cmds that are not blocked when a player is frozen and the above is true. Separate them with ";". For ex.: "help;say;list;etc."
    BLOCKED_COMMANDS_WHITELIST: ""
